#######################################################
# 
# AccountFactory.py
# Python implementation of the Class AccountFactory
# Generated by Enterprise Architect
# Created on:      09-Feb-2018 8:31:10 PM
# Original author: Sebastian
# 
#######################################################


class AccountFactory():
    def create_account(self, accType):


    pass