#######################################################
# 
# Account.py
# Python implementation of the Class Account
# Generated by Enterprise Architect
# Created on:      09-Feb-2018 8:31:10 PM
# Original author: Sebastian
# 
#######################################################
from view.BalanceView import BalanceView

class Account:
    """What are these
    """
    def __init__(self, observer, balance=0, accountName="anon", accType="Checking", color="white"):
        self.balance = balance
        self.accountName = accountName
        self.accType = accType
        self.color = color
        self.observer = observer


    def deposit(self, amt):
        self.balance += amt


    def withdraw(self, amt):
        self.balance -= amt
        pass

    def fire_balance_changed(self):

        pass
    m_BalanceView = BalanceView()
