#######################################################
# 
# BalanceView.py
# Python implementation of the Interface BalanceView
# Generated by Enterprise Architect
# Created on:      09-Feb-2018 8:31:10 PM
# Original author: Sebastian
# 
#######################################################


class BalanceView:
    """<<Interface>>"""
    def updateBalance(self):
        pass
    pass