#######################################################
# 
# CD.py
# Python implementation of the Class CD
# Generated by Enterprise Architect
# Created on:      09-Feb-2018 8:31:10 PM
# Original author: Sebastian
# 
#######################################################
from view.Account import Account

class CD(Account):
    pass