#######################################################
# 
# MainWindow.py
# Python implementation of the Class MainWindow
# Generated by Enterprise Architect
# Created on:      09-Feb-2018 8:31:10 PM
# Original author: Sebastian
# 
#######################################################
from view.BalanceView import BalanceView

class MainWindow(BalanceView):

    def __init__(self, accounts = None):
        if accounts == None:
            self.accounts = []

        pass

    def updateBallance(self):

        pass

    pass